# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: export.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'export.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65xport.proto\x12\x06\x65xport\"2\n\x13\x45xportImagesRequest\x12\x0e\n\x06\x61uthor\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x01(\t\"q\n\x13ImageExportResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x04 \x01(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t2`\n\x12ImageExportService\x12J\n\x0c\x45xportImages\x12\x1b.export.ExportImagesRequest\x1a\x1b.export.ImageExportResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'export_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXPORTIMAGESREQUEST']._serialized_start=24
  _globals['_EXPORTIMAGESREQUEST']._serialized_end=74
  _globals['_IMAGEEXPORTRESPONSE']._serialized_start=76
  _globals['_IMAGEEXPORTRESPONSE']._serialized_end=189
  _globals['_IMAGEEXPORTSERVICE']._serialized_start=191
  _globals['_IMAGEEXPORTSERVICE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
